name: Flutter CI

on: [push]

env:
  working-directory: './ble_control' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Flutter
      uses: steebchen/flutter@v1.0.0
      with:
        flutter-version: 1.12.13

    - name: Environment
      run: sudo apt update ; exec -l $SHELL ;

    - name: Install dependencies
      run: exec -l $SHELL ; flutter pub get

#     Doesn't have any tests yet
#     - name: Tests
#       run: flutter test

    - name: Build APK
      run: exec -l $SHELL ; flutter build apk --release

#     Only wors on Mac OS
#     - name: Build iOS
#       run: flutter build ios --release
